### ISSUE TITLE
Create a Rust function that extracts the attributes of all edges

### ISSUE THREAD

**Issue by MarIniOnz** [limebit/medmodels#133]
It will happen from a Data Scientist perspective that we will need to extract the numerical values contained in the edges between nodes and have an array as an output so that we can train new models. For instance here in "average_treatment_effect":

`    control_outcomes = np.array(
        [
            medrecord.edge[
                find_reference_edge(
                    medrecord,
                    node_index,
                    outcome_group,
                    time_attribute="time",
                    reference=reference,
                )
            ][outcome_variable]
            for node_index in control_true_set
        ]
    )`
    
It would be nice to have a way to extract those values directly.

Example:

Edge1 between node1 and node2, attribute: time = today
Edge2 between node1 and node2, attribute: time = yesterday

medrecord.edge_attributes(node1, node2, undirected=True, attributes = "time")

Output: array: today, yesterday

For multiple nodes:

nodes_1 (N size)
nodes_2(M size)

medrecord.edge_attributes(nodes_1, nodes_2, undirected=True, attributes = "time")

Matrix of lists: N x M . Each coordinate in the matrix has a list with the value of all edges connected Ni with Mi.

**Comment by JabobKrauskopf** [comment]
this is not a solution to any of the memory issues and is also possible right now.
