### ISSUE TITLE
Decide which functions go in the API reference documentation

### ISSUE THREAD

**Issue by MarIniOnz** [limebit/medmodels#162]
For now, the API Reference is full of functions that should not appear there, like tests.

We should create a convention of which functions should appear and which do not. This convention could also be included in the guidelines themselves.

**Comment by JabobKrauskopf** [comment]
@FloLimebit Can you handle this issue? (project management wise or development wise)

**Comment by FloLimebit** [comment]
I don't see any tests documented. Can you provide a specific example? @MarIniOnz

**Comment by MarIniOnz** [comment]
Okay, it is should in the docs-serve but still wrong in the webpage and that was what I meant. I guess it will be solved when the API reference is posted in the website. If that is the case @FloLimebit , please close this issue.

**Comment by MarIniOnz** [comment]
It is already solved.
