### ISSUE TITLE
Remove `add_node`, `add_edge` in favor of `add_nodes` and `add_edges`

### ISSUE THREAD

**Issue by JabobKrauskopf** [limebit/medmodels#224]
Remove the `add_node`, `add_edge` functions in favor of `add_nodes` and `add_edges` functions from the python medrecord as well as the `rustmodels` medrecord (the rust-to-python bindings) - including the `_medmodels.pyi` interface

**Comment by MarIniOnz** [comment]
Also, changing all singular to plural naming, i.e., `add_node_to group` into `add_nodes_to_group`
