### ISSUE TITLE
Adding an option to edges_connecting regardless of direction of the edge

### ISSUE THREAD

**Issue by MarIniOnz** [limebit/medmodels#92]
### Is your feature request related to a problem? Please describe.

Sometimes, it is not known to the user which one was the source and the target in the edge that connects them.

### Describe the solution you'd like

It would nice to add an option to `edges_connecting` that is direction = True or False for whether the direction matters or not for retrieving the edge IDs.

**Comment by JabobKrauskopf** [comment]
Now included in issue #101
